name: Java CI with Maven

on:
  push:
    # 分支
    branches: [ main ]

jobs:
  
  deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - run: mvn --batch-mode --update-snapshots package
      - run: mkdir deploay && cp target/*.jar deploay
        
      - name: Cache
        uses: actions/cache@v3.2.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Deploy the JAR file to the remote server
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Generate the package
        run: mvn -B package --file pom.xml -Dmaven.test.skip=true
        # 将jar包上传到服务器中
      - name: ssh-scp-ssh-pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
        with:
          host: ${{ secrets.HOST }}
          port: 22
          user: ${{ secrets.SSH_USER }}
          pass: ${{ secrets.SSH_PASSWORD }}
          # 复制本地jar包到远程服务器目录
          scp: |
            'deploay/*.jar' => /project/web/
          # 执行java -jar命令
          last_ssh: |
            cd blog.imzjw.cn/actions/ && java -jar github-actions-springboot.jar &
